// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAApte-ftj--HLa3MOr2TP4aqe481UGRMQ',
    appId: '1:519482028064:web:130bdc6248201d1928cc45',
    messagingSenderId: '519482028064',
    projectId: 'agrosell-ea91c',
    authDomain: 'agrosell-ea91c.firebaseapp.com',
    storageBucket: 'agrosell-ea91c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJE9CgbjerQ_cQAbeAeXphqINkSsCEvVc',
    appId: '1:519482028064:android:b3bb04d5d8c44f3b28cc45',
    messagingSenderId: '519482028064',
    projectId: 'agrosell-ea91c',
    storageBucket: 'agrosell-ea91c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLqecsByd7g940BxQXrG5Y6CsRHk4LeE4',
    appId: '1:519482028064:ios:e47cd30d1740515928cc45',
    messagingSenderId: '519482028064',
    projectId: 'agrosell-ea91c',
    storageBucket: 'agrosell-ea91c.appspot.com',
    iosClientId: '519482028064-08un4qd4fiqgm6hdpqukiu3auctrkrlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAdvancedBoilerplate',
  );
}
