// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqz0H6864WRNQwZ-IPCyM8L_7AyhUh5Go',
    appId: '1:119783059532:web:ba048f340eadb4fea0c4e9',
    messagingSenderId: '119783059532',
    projectId: 'agro-trade-c42b4',
    authDomain: 'agro-trade-c42b4.firebaseapp.com',
    storageBucket: 'agro-trade-c42b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWU7b4-hUmnT9KARdZJ96MkEM2wRwyKmc',
    appId: '1:119783059532:android:b50eb135357e48f6a0c4e9',
    messagingSenderId: '119783059532',
    projectId: 'agro-trade-c42b4',
    storageBucket: 'agro-trade-c42b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY8IylWdWedmSKTYpvLdz4PVs38LLGsVM',
    appId: '1:119783059532:ios:54364a133993d142a0c4e9',
    messagingSenderId: '119783059532',
    projectId: 'agro-trade-c42b4',
    storageBucket: 'agro-trade-c42b4.appspot.com',
    iosClientId: '119783059532-e10tv427nn687eri3rufhqv8sen0h52a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAdvancedBoilerplate',
  );
}
